### PR TITLE
[fix] close #1

### LINKED ISSUE #1: Bug with upcoming seasons next year
with `EC_ACTIVE_SEASON=WN15`

``` js
Calendar.activeSeason = { 
  id: 'WN15',
  code: 'WN',
  title: 'Winter 2015',
  dates:
  {
    charge: Tue Sep 15 2015 00:00:00 GMT-0500 (COT),
    ship: Tue Dec 01 2015 00:00:00 GMT-0500 (COT),
    inStore: Sat Aug 01 2015 00:00:00 GMT-0500 (COT)
  },
  startDate: Sat Aug 01 2015 00:00:00 GMT-0500 (COT),
  year: 2015,
  kind: 'winter'
}


Calendar.upcomingSeason = {
  id: 'SP15',
  code: 'SP',
  title: 'Spring 2015',
  dates:
  { charge: Mon Dec 15 2014 00:00:00 GMT-0500 (COT), // => NOTE THIS 2014
    ship: Sun Mar 01 2015 00:00:00 GMT-0500 (COT),
    inStore: Sun Nov 01 2015 00:00:00 GMT-0500 (COT) 
  },
  startDate: Sun Nov 01 2015 00:00:00 GMT-0500 (COT),
  year: 2015,
  kind: 'spring'
}
```

### PR DESCRIPTION
**Pull request by sescobb27**

### CODE REVIEW

File: dist/cjs/index.js [hunk 1]
```diff
@@ -20,10 +20,11 @@ var seasons = [];
 var firstYear = 2011;
 var currentYear = today.getFullYear();
 var nextYear = currentYear + 1;
+var nextTwoYear = currentYear + 2;
 var years = [];
 
-for (var i = nextYear - firstYear; i >= 0; i--) {
-  years.push(nextYear - i);
+for (var i = nextTwoYear - firstYear; i >= 0; i--) {
```
Comment (buritica) [inline dist/cjs/index.js]: Years is plural, nextTwoYears

**Comment by buritica** [comment]
besides that typo, lgtm merge after change
